import { StyleSheet as NativeStyleSheet } from "react-native";

const StyleSheet = Object.assign(NativeStyleSheet, {
  absoluteFillObject: {
    position: "absolute" as const,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 2,
  },
});

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: "#0b1020" },
  header: {
    padding: 24,
    paddingBottom: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  eyebrow: { color: "#7480a0", fontSize: 11, letterSpacing: 2 },
  heading: { color: "#f8fafc", fontSize: 30, fontWeight: "800", marginTop: 5 },
  addButton: {
    backgroundColor: "#6d5dfc",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  addText: { color: "#fff", fontWeight: "700" },
  feedTabsContainer: {
    borderBottomWidth: 1,
    paddingBottom: 10,
  },
  feedTabsContent: {
    gap: 8,
    paddingHorizontal: 16,
  },
  feedTab: {
    maxWidth: 180,
    borderWidth: 1,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 9,
  },
  feedTabText: { fontSize: 13, fontWeight: "800" },
  list: { padding: 16, paddingTop: 4, paddingBottom: 100, flexGrow: 1 },
  card: {
    backgroundColor: "#151d31",
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
  },
  cardMeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  source: { color: "#8f82ff", fontSize: 12, fontWeight: "700" },
  star: { color: "#f8c84e", fontSize: 25 },
  cardTitle: {
    color: "#f8fafc",
    fontSize: 17,
    lineHeight: 24,
    fontWeight: "700",
    marginTop: 7,
  },
  description: { color: "#aeb7ca", lineHeight: 20, marginTop: 8 },
  date: { color: "#6f7892", fontSize: 12, marginTop: 12 },
  empty: {
    color: "#8d98b1",
    textAlign: "center",
    marginTop: 100,
    lineHeight: 24,
  },
  tabs: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 76,
    backgroundColor: "#11182b",
    borderTopWidth: 1,
    borderTopColor: "#202b43",
    flexDirection: "row",
  },
  tab: { flex: 1, alignItems: "center", justifyContent: "center" },
  tabText: { color: "#6f7892", fontWeight: "700" },
  tabActive: { color: "#a69cff" },
  feedRow: {
    backgroundColor: "#151d31",
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  feedIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: "#29245e",
    justifyContent: "center",
    alignItems: "center",
  },
  feedIconText: { color: "#a69cff", fontSize: 11, fontWeight: "800" },
  feedInfo: { flex: 1, marginHorizontal: 12 },
  url: { color: "#7e89a5", marginTop: 4, fontSize: 12 },
  delete: { color: "#ff7f8a", fontSize: 12 },
  modalRoot: { flex: 1, justifyContent: "flex-end", backgroundColor: "#0008" },
  modal: {
    backgroundColor: "#151d31",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
  },
  modalTitle: {
    color: "#f8fafc",
    fontSize: 22,
    fontWeight: "800",
    marginBottom: 18,
  },
  input: {
    backgroundColor: "#0b1020",
    color: "#f8fafc",
    borderRadius: 12,
    padding: 14,
    marginBottom: 12,
  },
  feedSourceSelector: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  feedSourceButton: {
    flex: 1,
    alignItems: "center",
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 10,
  },
  feedSourceButtonText: { fontSize: 12, fontWeight: "800" },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 20,
    marginTop: 8,
  },
  cancel: { color: "#aeb7ca", fontWeight: "700" },
  save: {
    backgroundColor: "#6d5dfc",
    borderRadius: 12,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  saveText: { color: "#fff", fontWeight: "800" },
  webSafe: { flex: 1, backgroundColor: "#0b1020" },
  webHeader: {
    height: 54,
    backgroundColor: "#11182b",
    borderBottomWidth: 1,
    borderBottomColor: "#202b43",
    flexDirection: "row",
    alignItems: "center",
  },
  webBack: { width: 76, paddingHorizontal: 12, paddingVertical: 14 },
  webBackText: { color: "#a69cff", fontSize: 16, fontWeight: "700" },
  webTitle: {
    flex: 1,
    color: "#f8fafc",
    textAlign: "center",
    fontWeight: "700",
  },
  modeButton: { width: 76, alignItems: "center", paddingVertical: 9 },
  modeButtonText: { color: "#a69cff", fontSize: 12, fontWeight: "800" },
  webLoading: {
    position: "absolute",
    top: 54,
    left: 0,
    right: 0,
    zIndex: 3,
    paddingVertical: 8,
    backgroundColor: "#11182be6",
  },
  webContent: { flex: 1 },
  webView: { flex: 1, backgroundColor: "#fff" },
  readerView: { ...StyleSheet.absoluteFillObject, backgroundColor: "#f7f3ea" },
  readerWaiting: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "#f7f3ea",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  readerWaitingText: { color: "#706b63" },
  webToolbar: {
    height: 54,
    backgroundColor: "#11182b",
    borderTopWidth: 1,
    borderTopColor: "#202b43",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  webNavButton: {
    flex: 1,
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  webNavText: { color: "#a69cff", fontSize: 16, fontWeight: "700" },
  webNavDisabled: { color: "#46506a" },
});
